name: Build and Release APK

on:
  workflow_dispatch: # Allows manual triggering
  # push:
  #   tags:
  #     - 'v*.*.*' # Example: v1.0.0, v1.2.3-beta

permissions:
  contents: write # Required to create a release and upload assets

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle' # Cache Gradle dependencies

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Extract version name
        id: extract_version_name
        run: echo "VERSION_NAME=$(grep 'versionName ' app/build.gradle | sed -n 's/.*versionName "\(.*\)".*/\1/p')" >> $GITHUB_OUTPUT

      - name: Extract version code
        id: extract_version_code
        run: echo "VERSION_CODE=$(grep 'versionCode ' app/build.gradle | sed -n 's/.*versionCode \([0-9]*\).*/\1/p')" >> $GITHUB_OUTPUT

      - name: Build release APK
        run: ./gradlew :app:assembleRelease
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY_PLACEHOLDER }} # User needs to set this secret in repository settings

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.extract_version_name.outputs.VERSION_NAME }} # Prepend 'v' to version name for tag
          name: Release v${{ steps.extract_version_name.outputs.VERSION_NAME }}
          body: |
            ## Release v${{ steps.extract_version_name.outputs.VERSION_NAME }}
            **Build Number:** ${{ steps.extract_version_code.outputs.VERSION_CODE }}

            **Changelog:**
            * (Details of changes in this version - please fill in manually or automate)
          draft: false
          prerelease: false # Set to true if it's a pre-release (e.g., contains '-beta')
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
